name: Nightly Builds

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  compile-and-test:
    name: Compile and test
    runs-on: ubuntu-latest
    if: github.repository == 'apache/incubator-pekko-http'
    strategy:
      fail-fast: false
      matrix:
        SCALA_VERSION: [2.12, 2.13, 3]
        JDK: [8, 11, 17, 21]
        PEKKO_VERSION: ['default', 'main', '1.0.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK ${{ matrix.JDK }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.JDK }}

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Cache Build Target
        uses: actions/cache@v3
        with:
          path: project/**/target
          key: build-target-${{ hashFiles('**/*.sbt', 'project/build.properties', 'project/**/*.scala') }}

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: Compile everything
        run: sbt -Dpekko.http.build.pekko.version=${{ matrix.PEKKO_VERSION }} "++ ${{ matrix.SCALA_VERSION }}" Test/compile

      - name: Run all tests JDK ${{ matrix.JDK }}, Scala ${{ matrix.SCALA_VERSION }}, Pekko ${{ matrix.PEKKO_VERSION }}
        run: sbt -Dpekko.http.parallelExecution=false -Dpekko.test.timefactor=2 -Dpekko.http.build.pekko.version=${{ matrix.PEKKO_VERSION }} "++ ${{ matrix.SCALA_VERSION }}" mimaReportBinaryIssues test

      - name: Upload test results
        uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: test-results-${{ matrix.JDK }}-${{ matrix.SCALA_VERSION }}-${{ matrix.PEKKO_VERSION }}
          path: '**/target/test-reports/*.xml'
